[package]
name = "z-biz-tool-sys"
version = "0.1.0"
description = "系统监控仪表盘 - 对标iStat Menus/Stats"
edition = "2021"
license = "MIT"

[lib]
name = "z_biz_tool_sys_lib"
crate-type = ["lib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.33"
libc = "0.2"
tokio = { version = "1", features = ["full"] }
dirs = "5"
walkdir = "2"
regex = "1"
tauri-plugin-notification = "2.4.0"
